# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

     app.repository.user:
         class: Doctrine\ORM\EntityRepository
         factory: ['@doctrine.orm.default_entity_manager', getRepository]
         arguments: [AppBundle\Entity\User]

     app.service.user:
         class: AppBundle\Service\User
         arguments: ['@app.repository.user', '@doctrine.orm.entity_manager']

     app.front.controller:
         class: AppBundle\Controller\FrontController
         arguments: ['@templating.engine.twig']

     app.api.controller:
         class: AppBundle\Controller\ApiController
         arguments: ['@app.service.user']

     app.api.user.controller:
         class: AppBundle\Controller\UserController
         arguments: ['@app.service.user']
