# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

     app.repository.user:
         class: Doctrine\ORM\EntityRepository
         factory: ['@doctrine.orm.default_entity_manager', getRepository]
         arguments: [AppBundle\Entity\User]

     app.repository.employee:
         class: Doctrine\ORM\EntityRepository
         factory: ['@doctrine.orm.default_entity_manager', getRepository]
         arguments: [AppBundle\Entity\Employee]

     app.service.user:
         class: AppBundle\Service\User
         arguments: ['@app.repository.user', '@doctrine.orm.entity_manager']

     app.service.employee:
         class: AppBundle\Service\Employee
         arguments: ['@app.repository.employee', '@doctrine.orm.entity_manager']

     app.front.controller:
         class: AppBundle\Controller\FrontController
         arguments: ['@templating.engine.twig']

     app.api.controller:
         class: AppBundle\Controller\ApiController
         calls:
             - [setServiceUser, ['@app.service.user']]

     app.api.user.controller:
         class: AppBundle\Controller\UserController
         calls:
             - [setServiceUser, ['@app.service.user']]

     app.api.employee.controller:
         class: AppBundle\Controller\EmployeeController
         calls:
             - [setServiceUser, ['@app.service.user']]
             - [setServiceEmployee, ['@app.service.employee']]
