
login:
    path:     /login
    defaults: { _controller: app.api.controller:loginAction }

user.create:
    path:     /user/create
    defaults: { _controller: app.api.user.controller:createAction }

user.update:
    path:     /user/{id}
    defaults: { _controller: app.api.user.controller:updateAction }
    methods:  [PUT]

user.delete:
    path:     /user/{id}
    defaults: { _controller: app.api.user.controller:deleteAction }
    methods:  [DELETE]
