
login:
    path:     /login
    defaults: { _controller: app.api.controller:loginAction }

user.get:
    path:     /user
    defaults: { _controller: app.api.user.controller:findAction }
    methods:  [GET]

user.create:
    path:     /user
    defaults: { _controller: app.api.user.controller:createAction }
    methods:  [POST]

user.update:
    path:     /user/{id}
    defaults: { _controller: app.api.user.controller:updateAction }
    methods:  [PUT]

user.delete:
    path:     /user/{id}
    defaults: { _controller: app.api.user.controller:deleteAction }
    methods:  [DELETE]
