AppBundle\Entity\Employee:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EmployeeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        first_name:
            type: string
            length: 255
        last_name:
            type: string
            length: 255
        surname:
            type: string
            length: 255
        birthdate:
            type: date
        salary:
            type: float
    lifecycleCallbacks: {  }
